### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by QuantumTarantino** [shobrook/rebound#44]
I'm getting the same error as in #41 . Maybe stackoverflow changed again?. Browser redirect works fine.

Traceback (most recent call last):
  File "/home/xxxx/.local/bin/rebound", line 11, in <module>
    sys.exit(main())
  File "/home/xxxx/.local/lib/python3.6/site-packages/rebound/rebound.py", line 844, in main
    App(search_results) # Opens interface
  File "/home/xxxx/.local/lib/python3.6/site-packages/rebound/rebound.py", line 733, in __init__
    self.main_loop.run()
  File "/home/xxxx/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/xxxx/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/home/xxxx/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/home/xxxx/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/home/xxxx/.local/lib/python3.6/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/xxxx/.local/lib/python3.6/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/home/xxxx/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/home/xxxx/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 517, in process_input
    something_handled |= bool(self.unhandled_input(k))
  File "/home/xxxx/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 563, in unhandled_input
    return self._unhandled_input(input)
  File "/home/xxxx/.local/lib/python3.6/site-packages/rebound/rebound.py", line 742, in _handle_input
    question_title, question_desc, question_stats, answers = get_question_and_answers(url)
  File "/home/xxxx/.local/lib/python3.6/site-packages/rebound/rebound.py", line 307, in get_question_and_answers
    question_stats = soup.find_all("span", class_="vote-count-post")[0].get_text() # Vote count
IndexError: list index out of range

**Comment by QuantumTarantino** [comment]
I changed line 307 at rebound.py:
question_stats = soup.find_all("span", class="vote-count-post")[0].get_text() # Vote count

for this:
question_stats = soup.find("div", class_="js-vote-count").get_text() # Vote count

now works again.
