### ISSUE TITLE
Doesn't work on Cygwin either

### ISSUE THREAD

**Issue by Sushanti99** [shobrook/rebound#51]
Hey! I tried installing Cygwin and running a code with error but I get the same message that I was getting while running it on PowerShell. The error looks like this:

```
$ rebound error.py
Traceback (most recent call last):
  File "c:\anaconda_3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda_3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda_3\Scripts\rebound.exe\__main__.py", line 9, in <module>
  File "c:\anaconda_3\lib\site-packages\rebound\rebound.py", line 856, in main
    output, error = execute([language] + file_path) # Compiles the file and pipes stdout
  File "c:\anaconda_3\lib\site-packages\rebound\rebound.py", line 170, in execute
    bufsize=1
  File "c:\anaconda_3\lib\subprocess.py", line 624, in __init__
    "close_fds is not supported on Windows platforms"
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr
```
Any solution to this?

**Comment by UchihaSR** [comment]
Change the value of close_fds=True to close_fds=(sys.platform != 'win32') which is inside th rebound.py
