### ISSUE TITLE
File Not Found Error 

### ISSUE THREAD

**Issue by zeeshantariqrafique** [shobrook/rebound#73]
$ rebound main.py
Traceback (most recent call last):
  File "c:\users\zeeshan rafique\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\zeeshan rafique\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Zeeshan Rafique\anaconda3\Scripts\rebound.exe\__main__.py", line 7, in <module>
  File "c:\users\zeeshan rafique\anaconda3\lib\site-packages\rebound\rebound.py", line 856, in main
    output, error = execute([language] + file_path) # Compiles the file and pipes stdout
  File "c:\users\zeeshan rafique\anaconda3\lib\site-packages\rebound\rebound.py", line 170, in execute
    bufsize=1
  File "c:\users\zeeshan rafique\anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\users\zeeshan rafique\anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by shobrook** [comment]
This means `main.py` doesn't exist in the directory you're running this in. If you run `$ python main.py` you should get a `No such file or directory` error. If you don't, then feel free to reopen this issue.
