### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by kshitij86** [shobrook/rebound#79]
Installed `rebound` with `pip v20.0.2`. When running a simple Python file with a syntax error, produces the following -
```
Traceback (most recent call last):
  File "/home/user86/.local/bin/rebound", line 5, in <module>
    from rebound.rebound import main
  File "/home/user86/.local/lib/python3.6/site-packages/rebound/rebound.py", line 6, in <module>
    import urwid
  File "/home/user86/.local/lib/python3.6/site-packages/urwid/__init__.py", line 26, in <module>
    from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
  File "/home/user86/.local/lib/python3.6/site-packages/urwid/widget.py", line 27, in <module>
    from urwid.util import (MetaSuper, decompose_tagmarkup, calc_width,
  File "/home/user86/.local/lib/python3.6/site-packages/urwid/util.py", line 61, in <module>
    detected_encoding = detect_encoding()
  File "/home/user86/.local/lib/python3.6/site-packages/urwid/util.py", line 58, in detect_encoding
    locale.setlocale(locale.LC_ALL, initial)
  File "/usr/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)

```
What could be causing this?

**Comment by kshitij86** [comment]
Was a pip error. Solved by ```export LC_ALL=C```
